### PR TITLE
subordinate / issuing CA profile updates

### PR DESCRIPTION
**Pull request by lachellel**
#78 

adding more...stay tuned...

(updated issue reference)

### CODE REVIEW

**Comment by lachellel** [comment]
@tlsrus
@larryfrank
@techliaison
@mttcpr2

updates from #78 - please review and comment!

**Comment by lachellel** [comment]
updated per techliaison comments
going to apply to root profile

**Comment by LarryFrank** [comment]
The one I might take exception to is the private extensions - it is unlikely to occur because these are supposed to be public facing systems and a private extension is unlikely to be understood outside the agency which wants it.  That being said - it SHALL be marked non-critical, so it can be safely ignored by systems which do not understand - so why require PA approval?  Sorry if this was discussed while I was on leave - feel free to say that!

**Comment by lachellel** [comment]
@LarryFrank 
I think you're aligned with the intent for private extensions and adding the PA approval
A short discussion encompassed those instances where one or more CA **products** insert private extensions that are specific to their product sets - which occurs.  Generally the agency does not need it or specify it.

**Comment by konklone** [comment]
We also discussed potentially requiring any participating commercial CAs to suppress adding any such private extensions into certificates issued for the US government.

**Comment by lachellel** [comment]
@konklone 
merge?

**Pull request merged**
