### PR TITLE
OCSP certificate profile updates

### PR DESCRIPTION
**Pull request by lachellel**
updates for #86

### CODE REVIEW

**Comment by lachellel** [comment]
@mttcpr2 @techliaison @LarryFrank

Looking for initial review?
few items outstanding in #86

**Comment by lachellel** [comment]
@mttcpr2 can you review?  I had to refresh my memory; and added the additional comments in #86. 

Did not explicitly make the CDP not permitted but open to changes!

**Comment by techliaison** [comment]
why did you add SAN as optional and then mandate it must be a FQDN if present?
Does anyone include SAN in the OCSP responder cert, I haven't seen it in the samples I looked at under the FPKI.

**Comment by LarryFrank** [comment]
DoD has the SAN "optional" in its OCSP certs (cannot say whether it actually is present or not).  CDP is also optional (sorta) - required if no-check is not included.  Not allowed if No-check is included.

**Comment by techliaison** [comment]
Can anyone provide an example of what SANs might be in an OCSP responder cert?
I ask because I don’t see any in use although I haven’t seen a Symantec one and I know they have used SAN in CA certificates that is a Directory Address with just a CN that indicates something about the CA.  I’m wondering they do something similar with their OCSP responder certs that would be different from the FQDN you are suggesting is the only valid format if SAN is present

**Pull request merged**
