### PR TITLE
Microsoft and Mozilla merges

### PR DESCRIPTION
**Pull request by lachellel**
We have two branches that got out of sync...
Conflict on changes.
Review for conflicts...

### CODE REVIEW

**Comment by lachellel** [comment]
@weirdscience 
the two branches with microsoft in name had conflicts. one had reversions. 
looking at the conflicts and the changes: 

- We keep what's currently in master?  And then we close this PR and delete the MicrosoftTrust branch. 
- **Did we miss any of the requirements you had added?**

**Comment by lachellel** [comment]
@weirdscience 

An open question - of the conflicts (there are three), which were intended to address the Microsoft or other trust store requirements?  Which should be kept and which should be discarded?

Look at "resolve conflicts" to view the conflicts.

**Comment by weirdscience** [comment]
I resolved the conflicts.

**Comment by lachellel** [comment]
let's merge and then the other PRs may already modify / overwrite

@konklone agree?

**Pull request merged**
